coin_ids:
  - bitcoin
  - ethereum
  - ripple
  - tether
  - bitcoin-cash
  - bitcoin-cash-sv
  - litecoin
  - eos
  - binancecoin
  - tezos

max_retries: 10
request_delay: 0.15
concurrent_requests: 10

smart_scan: false
