coin_ids:
  - bitcoin
  - ethereum
  - ripple
  - tether
  - bitcoin-cash
  - bitcoin-cash-sv
  - litecoin
  - eos
  - binancecoin
  - tezos

max_retries: 10
rate_limit: 60
rate_timeframe: 60
concurrent_requests: 10

smart_scan: false
