coin_ids:
  - bitcoin
  - ethereum
  - ripple
  - tether
  - bitcoin-cash
  - bitcoin-cash-sv
  - litecoin
  - eos
  - binancecoin
  - tezos

max_retries: 10
rate_limit: 60
rate_timeframe: 60
concurrent_requests: 10

requests_cache: cache

smart_scan: false


databases:
  mongodb:
  sqlite:
  redis:
  postgresql:
  sqlite:

message_brokers:
  rabbitmq:
    host: localhost
    port: port
    'amqp://myuser:mypassword@localhost:5672/myvhost'
  redis:
    host:
    port:
       'redis://:password@hostname:port/db_number'
  sqs: 'sqs://ABCDEFGHIJKLMNOPQRST:ZYXK7NiynGlTogH8Nj+P9nlE73sq3@'
  zookeeper: none

connections:
  requests_cache:
    backend:
  task_queue:
    broker: 
      rabbitmq: 
        host: rabbitmq
        port: 5672
        user: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
        virtualhost: 
    serialization:
      type:
      parameters:

destinations:
  - domain: coingecko.com
    proxy: false
    rate_limit:
      requests: 60
      timeframe: 60
  - domain: archived.moe
    proxy: true
    rate_limit:
      requests: 100
      timeframe: 60
  - domain: pushshift.io
    proxy: true
    rate_limit:
      requests: 100
      timeframe: 60
  - domain: reddit.com
    proxy: true
    rate_limit:
      requests: 100
      timeframe: 60
