version: '3'

services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coingecko
    restart: always

  coingecko:
    build: ./coingecko
    ports:
      - 5001:5001
    volumes:
      - ./coingecko:/app # for debug mode - not neccessary for production
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coingecko 
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    restart: always
    depends_on:
        - postgres

volumes:
  postgres:
    driver: local
