version: "3"

services:
  # tor:
  #   image: osminogin/tor-simple
  #   restart: always
  #   ports:
  #     - 127.0.0.1:9050:9050
  #     - 127.0.0.1:9150:9150

  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUALHOST}
    restart: always

  workers:
    image: python:3.6
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VIRTUALHOST}
    restart: always
