version: "3"

services:
  tor:
    image: osminogin/tor-simple
    restart: always
    ports:
      - 127.0.0.1:9050:9050
      - 127.0.0.1:9150:9150

  redis:
    image: redis:6.0-buster
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_DB_NUMBER: ${REDIS_DB_NUMBER}
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUALHOST}
    restart: always

  workers:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - tor
    command: celery -A cryb.worker worker -l info -c 10 -Q coingecko.com -O fair

  scheduler:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - workers
    command: celery -A cryb.scheduler beat -l info

  crawlers:
    build: .
    # command: cryb crawlers
    # restart: always

  monitor:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
    command: --broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${RABBITMQ_PORT}/${RABBITMQ_VIRTUALHOST}
