version: "3"

services:
  # tor:
  #   image: osminogin/tor-simple
  #   restart: always
  #   ports:
  #     - 127.0.0.1:9050:9050
  #     - 127.0.0.1:9150:9150

  redis:
    image: redis:6.0-buster
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 5 100
    environment:
      REDIS_DB_NUMBER: ${REDIS_DB_NUMBER}
    volumes:
      - ./data/redis:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUALHOST}
    restart: always

  postgres:
    image: postgres:12.4-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always

  memcached:
    image: memcached:1.6
    ports:
      - ${MEMCACHED_PORT}:${MEMCACHED_PORT}
    restart: always

  workers:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - rabbitmq
      - redis
      # - tor
      - postgres
    command: celery -A cryb.worker worker -l info -c 10 -Q 4cdn.org,coingecko.com,reddit.com -O fair

  scheduler:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - workers
    user: root
    command: celery -A cryb.scheduler beat

  fourchan_crawler:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - workers
    user: root
    command: cryb crawl -c fourchan

  coingecko_crawler:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - workers
    user: root
    command: cryb crawl -c coingecko

  reddit_crawler:
    build: .
    env_file:
      - .env
    volumes:
      - ./cryb:/app/cryb
    restart: always
    depends_on:
      - workers
    user: root
    command: cryb crawl -c reddit

  monitor:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
    restart: always
    command: --broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:${RABBITMQ_PORT}/${RABBITMQ_VIRTUALHOST}

  grafana:
    image: grafana/grafana:7.1.3
    ports:
      - 3000:3000
    # volumes:
    #   - ./data/grafana:/var/lib/grafana
    depends_on:
      - postgres
    restart: always
