# parameters to be recategorized
timeseries_start: 2015-01-01
fourchan_boards:
  - biz
reddit_boards:
  - bitcoin

connections:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database_number: ${REDIS_DB_NUMBER}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    user: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtualhost: ${RABBITMQ_VIRTUALHOST}

  postgres:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DATABASE}

  memcached:
    host: ${MEMCACHED_HOST}
    port: ${MEMCACHED_PORT}

targets:
  - domain: coingecko.com
    proxy: false
    cache: true
    concurrency: 10
    max_retries: 10
    rate_limit:
      requests: 60
      timeframe: 60
  - domain: 4cdn.org
    proxy: false
    cache: false
    concurrency: 10
    max_retries: 10
    rate_limit:
      requests: 60
      timeframe: 60
  - domain: pushshift.io
    proxy: true
    cache: false
    concurrency: 10
    max_retries: 10
    rate_limit:
      requests: 60
      timeframe: 60
  - domain: reddit.com
    proxy: true
    cache: false
    concurrency: 10
    max_retries: 10
    rate_limit:
      requests: 30
      timeframe: 60
