coin_ids:
  - bitcoin
  - ethereum
  - ripple
  - tether
  - bitcoin-cash
  - bitcoin-cash-sv
  - litecoin
  - eos
  - binancecoin
  - tezos

connections:
  requests_cache:
    backend:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
        db_number: ${REDIS_DB_NUMBER}
  task_queue:
    broker:
      rabbitmq:
        host: rabbitmq
        port: ${RABBITMQ_PORT}
        user: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
        virtualhost: ${RABBITMQ_PASSWORD}
    # serialization:
    #   type:
    #   parameters:

destinations:
  - domain: coingecko.com
    proxy: false
    rate_limit:
      requests: 60
      timeframe: 60
  - domain: archived.moe
    proxy: true
    rate_limit:
      requests: 100
      timeframe: 60
  - domain: pushshift.io
    proxy: true
    rate_limit:
      requests: 100
      timeframe: 60
  - domain: reddit.com
    proxy: true
    rate_limit:
      requests: 100
      timeframe: 60
